/*
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.robotml.ui.internal.RobotmlActivator;

public class RobotMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RobotmlActivator.getInstance().getInjector("org.xtext.robotml.RobotML");
	}

}
