/**
 *
 * $Id$
 */
package robotML.validation;

import org.eclipse.emf.common.util.EList;

import robotML.Expression;
import robotML.Operators;

/**
 * A sample validator interface for {@link robotML.Binary}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BinaryValidator {
	boolean validate();

	boolean validateOperands(EList<Expression> value);

	boolean validateOperator(Operators value);
}
