/*
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.robotml.parser.antlr.internal.InternalRobotMLParser;
import org.xtext.robotml.services.RobotMLGrammarAccess;

public class RobotMLParser extends AbstractAntlrParser {

	@Inject
	private RobotMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRobotMLParser createParser(XtextTokenStream stream) {
		return new InternalRobotMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Assignation";
	}

	public RobotMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RobotMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
