/*
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.robotml.ide.contentassist.antlr.internal.InternalRobotMLParser;
import org.xtext.robotml.services.RobotMLGrammarAccess;

public class RobotMLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(RobotMLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, RobotMLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
			builder.put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getBinaryOpAccess().getAlternatives(), "rule__BinaryOp__Alternatives");
			builder.put(grammarAccess.getUnaryOpAccess().getAlternatives(), "rule__UnaryOp__Alternatives");
			builder.put(grammarAccess.getSensorAccess().getAlternatives(), "rule__Sensor__Alternatives");
			builder.put(grammarAccess.getAssignationAccess().getGroup(), "rule__Assignation__Group__0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getGroup(), "rule__VariableDeclaration__Group__0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getGroup_4(), "rule__VariableDeclaration__Group_4__0");
			builder.put(grammarAccess.getString0Access().getGroup(), "rule__String0__Group__0");
			builder.put(grammarAccess.getBooleanAccess().getGroup(), "rule__Boolean__Group__0");
			builder.put(grammarAccess.getIntegerAccess().getGroup(), "rule__Integer__Group__0");
			builder.put(grammarAccess.getFloatAccess().getGroup(), "rule__Float__Group__0");
			builder.put(grammarAccess.getVoidAccess().getGroup(), "rule__Void__Group__0");
			builder.put(grammarAccess.getFunctionCallAccess().getGroup(), "rule__FunctionCall__Group__0");
			builder.put(grammarAccess.getFunctionCallAccess().getGroup_4(), "rule__FunctionCall__Group_4__0");
			builder.put(grammarAccess.getFunctionCallAccess().getGroup_4_3(), "rule__FunctionCall__Group_4_3__0");
			builder.put(grammarAccess.getBinaryAccess().getGroup(), "rule__Binary__Group__0");
			builder.put(grammarAccess.getBinaryAccess().getGroup_2(), "rule__Binary__Group_2__0");
			builder.put(grammarAccess.getBinaryAccess().getGroup_8(), "rule__Binary__Group_8__0");
			builder.put(grammarAccess.getBinaryAccess().getGroup_13(), "rule__Binary__Group_13__0");
			builder.put(grammarAccess.getUnaryAccess().getGroup(), "rule__Unary__Group__0");
			builder.put(grammarAccess.getUnaryAccess().getGroup_2(), "rule__Unary__Group_2__0");
			builder.put(grammarAccess.getUnaryAccess().getGroup_8(), "rule__Unary__Group_8__0");
			builder.put(grammarAccess.getVariableRefAccess().getGroup(), "rule__VariableRef__Group__0");
			builder.put(grammarAccess.getGetSpeedAccess().getGroup(), "rule__GetSpeed__Group__0");
			builder.put(grammarAccess.getGetClockAccess().getGroup(), "rule__GetClock__Group__0");
			builder.put(grammarAccess.getGetSensorAccess().getGroup(), "rule__GetSensor__Group__0");
			builder.put(grammarAccess.getGetSensorAccess().getGroup_2(), "rule__GetSensor__Group_2__0");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getGroup(), "rule__FunctionDeclaration__Group__0");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getGroup_6(), "rule__FunctionDeclaration__Group_6__0");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getGroup_6_3(), "rule__FunctionDeclaration__Group_6_3__0");
			builder.put(grammarAccess.getBlockAccess().getGroup(), "rule__Block__Group__0");
			builder.put(grammarAccess.getBlockAccess().getGroup_3(), "rule__Block__Group_3__0");
			builder.put(grammarAccess.getBlockAccess().getGroup_3_3(), "rule__Block__Group_3_3__0");
			builder.put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_5(), "rule__Condition__Group_5__0");
			builder.put(grammarAccess.getConditionAccess().getGroup_10(), "rule__Condition__Group_10__0");
			builder.put(grammarAccess.getSetSpeedAccess().getGroup(), "rule__SetSpeed__Group__0");
			builder.put(grammarAccess.getSetClockAccess().getGroup(), "rule__SetClock__Group__0");
			builder.put(grammarAccess.getRotateAccess().getGroup(), "rule__Rotate__Group__0");
			builder.put(grammarAccess.getForwardAccess().getGroup(), "rule__Forward__Group__0");
			builder.put(grammarAccess.getBackwardAccess().getGroup(), "rule__Backward__Group__0");
			builder.put(grammarAccess.getLeftwardAccess().getGroup(), "rule__Leftward__Group__0");
			builder.put(grammarAccess.getRightwardAccess().getGroup(), "rule__Rightward__Group__0");
			builder.put(grammarAccess.getAssignationAccess().getVariableDeclAssignment_3(), "rule__Assignation__VariableDeclAssignment_3");
			builder.put(grammarAccess.getAssignationAccess().getExpressionAssignment_5(), "rule__Assignation__ExpressionAssignment_5");
			builder.put(grammarAccess.getVariableDeclarationAccess().getNameAssignment_2(), "rule__VariableDeclaration__NameAssignment_2");
			builder.put(grammarAccess.getVariableDeclarationAccess().getTypeAssignment_4_1(), "rule__VariableDeclaration__TypeAssignment_4_1");
			builder.put(grammarAccess.getFunctionCallAccess().getFunctiondeclarationAssignment_3(), "rule__FunctionCall__FunctiondeclarationAssignment_3");
			builder.put(grammarAccess.getFunctionCallAccess().getParametersAssignment_4_2(), "rule__FunctionCall__ParametersAssignment_4_2");
			builder.put(grammarAccess.getFunctionCallAccess().getParametersAssignment_4_3_1(), "rule__FunctionCall__ParametersAssignment_4_3_1");
			builder.put(grammarAccess.getFunctionCallAccess().getExpresionAssignment_6(), "rule__FunctionCall__ExpresionAssignment_6");
			builder.put(grammarAccess.getBinaryAccess().getOperatorAssignment_2_1(), "rule__Binary__OperatorAssignment_2_1");
			builder.put(grammarAccess.getBinaryAccess().getExpresionAssignment_4(), "rule__Binary__ExpresionAssignment_4");
			builder.put(grammarAccess.getBinaryAccess().getExpressionAssignment_7(), "rule__Binary__ExpressionAssignment_7");
			builder.put(grammarAccess.getBinaryAccess().getExpressionAssignment_8_1(), "rule__Binary__ExpressionAssignment_8_1");
			builder.put(grammarAccess.getBinaryAccess().getOperandsAssignment_12(), "rule__Binary__OperandsAssignment_12");
			builder.put(grammarAccess.getBinaryAccess().getOperandsAssignment_13_1(), "rule__Binary__OperandsAssignment_13_1");
			builder.put(grammarAccess.getUnaryAccess().getOperatorAssignment_2_1(), "rule__Unary__OperatorAssignment_2_1");
			builder.put(grammarAccess.getUnaryAccess().getExpresionAssignment_4(), "rule__Unary__ExpresionAssignment_4");
			builder.put(grammarAccess.getUnaryAccess().getExpressionAssignment_7(), "rule__Unary__ExpressionAssignment_7");
			builder.put(grammarAccess.getUnaryAccess().getExpressionAssignment_8_1(), "rule__Unary__ExpressionAssignment_8_1");
			builder.put(grammarAccess.getUnaryAccess().getOperandAssignment_11(), "rule__Unary__OperandAssignment_11");
			builder.put(grammarAccess.getVariableRefAccess().getRefAssignment_3(), "rule__VariableRef__RefAssignment_3");
			builder.put(grammarAccess.getVariableRefAccess().getExpresionAssignment_5(), "rule__VariableRef__ExpresionAssignment_5");
			builder.put(grammarAccess.getGetSpeedAccess().getExpresionAssignment_3(), "rule__GetSpeed__ExpresionAssignment_3");
			builder.put(grammarAccess.getGetClockAccess().getExpresionAssignment_3(), "rule__GetClock__ExpresionAssignment_3");
			builder.put(grammarAccess.getGetSensorAccess().getSensorAssignment_2_1(), "rule__GetSensor__SensorAssignment_2_1");
			builder.put(grammarAccess.getGetSensorAccess().getExpresionAssignment_4(), "rule__GetSensor__ExpresionAssignment_4");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getReturnTypeAssignment_3(), "rule__FunctionDeclaration__ReturnTypeAssignment_3");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getBlockAssignment_5(), "rule__FunctionDeclaration__BlockAssignment_5");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getParametersAssignment_6_2(), "rule__FunctionDeclaration__ParametersAssignment_6_2");
			builder.put(grammarAccess.getFunctionDeclarationAccess().getParametersAssignment_6_3_1(), "rule__FunctionDeclaration__ParametersAssignment_6_3_1");
			builder.put(grammarAccess.getBlockAccess().getStatementsAssignment_3_2(), "rule__Block__StatementsAssignment_3_2");
			builder.put(grammarAccess.getBlockAccess().getStatementsAssignment_3_3_1(), "rule__Block__StatementsAssignment_3_3_1");
			builder.put(grammarAccess.getConditionAccess().getBlockAssignment_4(), "rule__Condition__BlockAssignment_4");
			builder.put(grammarAccess.getConditionAccess().getBlockAssignment_5_1(), "rule__Condition__BlockAssignment_5_1");
			builder.put(grammarAccess.getConditionAccess().getConditionsAssignment_9(), "rule__Condition__ConditionsAssignment_9");
			builder.put(grammarAccess.getConditionAccess().getConditionsAssignment_10_1(), "rule__Condition__ConditionsAssignment_10_1");
			builder.put(grammarAccess.getSetSpeedAccess().getExpressionAssignment_3(), "rule__SetSpeed__ExpressionAssignment_3");
			builder.put(grammarAccess.getSetClockAccess().getExpressionAssignment_3(), "rule__SetClock__ExpressionAssignment_3");
			builder.put(grammarAccess.getRotateAccess().getExpressionAssignment_3(), "rule__Rotate__ExpressionAssignment_3");
			builder.put(grammarAccess.getForwardAccess().getExpressionAssignment_3(), "rule__Forward__ExpressionAssignment_3");
			builder.put(grammarAccess.getBackwardAccess().getExpressionAssignment_3(), "rule__Backward__ExpressionAssignment_3");
			builder.put(grammarAccess.getLeftwardAccess().getExpressionAssignment_3(), "rule__Leftward__ExpressionAssignment_3");
			builder.put(grammarAccess.getRightwardAccess().getExpressionAssignment_3(), "rule__Rightward__ExpressionAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private RobotMLGrammarAccess grammarAccess;

	@Override
	protected InternalRobotMLParser createParser() {
		InternalRobotMLParser result = new InternalRobotMLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public RobotMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RobotMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
