/*
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RobotMLGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class AssignationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Assignation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAssignationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cVariableDeclKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cVariableDeclAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cVariableDeclVariableDeclarationParserRuleCall_3_0 = (RuleCall)cVariableDeclAssignment_3.eContents().get(0);
		private final Keyword cExpressionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cExpressionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cExpressionExpressionParserRuleCall_5_0 = (RuleCall)cExpressionAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Assignation returns Assignation:
		//    'Assignation'
		//    '{'
		//        'variableDecl' variableDecl=VariableDeclaration
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Assignation'
		//'{'
		//    'variableDecl' variableDecl=VariableDeclaration
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Assignation'
		public Keyword getAssignationKeyword_0() { return cAssignationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'variableDecl'
		public Keyword getVariableDeclKeyword_2() { return cVariableDeclKeyword_2; }
		
		//variableDecl=VariableDeclaration
		public Assignment getVariableDeclAssignment_3() { return cVariableDeclAssignment_3; }
		
		//VariableDeclaration
		public RuleCall getVariableDeclVariableDeclarationParserRuleCall_3_0() { return cVariableDeclVariableDeclarationParserRuleCall_3_0; }
		
		//'expression'
		public Keyword getExpressionKeyword_4() { return cExpressionKeyword_4; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_5() { return cExpressionAssignment_5; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_5_0() { return cExpressionExpressionParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Expression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFunctionCallParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBinaryParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cUnaryParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cVariableRefParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cGetSpeedParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cGetClockParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cGetSensorParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Expression returns Expression:
		//    FunctionCall | Binary | Unary | VariableRef | GetSpeed | GetClock | GetSensor;
		@Override public ParserRule getRule() { return rule; }
		
		//FunctionCall | Binary | Unary | VariableRef | GetSpeed | GetClock | GetSensor
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FunctionCall
		public RuleCall getFunctionCallParserRuleCall_0() { return cFunctionCallParserRuleCall_0; }
		
		//Binary
		public RuleCall getBinaryParserRuleCall_1() { return cBinaryParserRuleCall_1; }
		
		//Unary
		public RuleCall getUnaryParserRuleCall_2() { return cUnaryParserRuleCall_2; }
		
		//VariableRef
		public RuleCall getVariableRefParserRuleCall_3() { return cVariableRefParserRuleCall_3; }
		
		//GetSpeed
		public RuleCall getGetSpeedParserRuleCall_4() { return cGetSpeedParserRuleCall_4; }
		
		//GetClock
		public RuleCall getGetClockParserRuleCall_5() { return cGetClockParserRuleCall_5; }
		
		//GetSensor
		public RuleCall getGetSensorParserRuleCall_6() { return cGetSensorParserRuleCall_6; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cString0ParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBooleanParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIntegerParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFloatParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cVoidParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Type returns Type:
		//    String0 | Boolean | Integer | Float | Void;
		@Override public ParserRule getRule() { return rule; }
		
		//String0 | Boolean | Integer | Float | Void
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//String0
		public RuleCall getString0ParserRuleCall_0() { return cString0ParserRuleCall_0; }
		
		//Boolean
		public RuleCall getBooleanParserRuleCall_1() { return cBooleanParserRuleCall_1; }
		
		//Integer
		public RuleCall getIntegerParserRuleCall_2() { return cIntegerParserRuleCall_2; }
		
		//Float
		public RuleCall getFloatParserRuleCall_3() { return cFloatParserRuleCall_3; }
		
		//Void
		public RuleCall getVoidParserRuleCall_4() { return cVoidParserRuleCall_4; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cFunctionDeclarationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBlockParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cAssignationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cVariableDeclarationParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cFunctionCallParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cConditionParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cSetSpeedParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cSetClockParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cRotateParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cForwardParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		private final RuleCall cBackwardParserRuleCall_10 = (RuleCall)cAlternatives.eContents().get(10);
		private final RuleCall cLeftwardParserRuleCall_11 = (RuleCall)cAlternatives.eContents().get(11);
		private final RuleCall cRightwardParserRuleCall_12 = (RuleCall)cAlternatives.eContents().get(12);
		
		//Statement returns Statement:
		//    FunctionDeclaration | Block | Assignation | VariableDeclaration | FunctionCall | Condition | setSpeed | SetClock | Rotate | Forward | Backward | Leftward | Rightward;
		@Override public ParserRule getRule() { return rule; }
		
		//FunctionDeclaration | Block | Assignation | VariableDeclaration | FunctionCall | Condition | setSpeed | SetClock | Rotate | Forward | Backward | Leftward | Rightward
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FunctionDeclaration
		public RuleCall getFunctionDeclarationParserRuleCall_0() { return cFunctionDeclarationParserRuleCall_0; }
		
		//Block
		public RuleCall getBlockParserRuleCall_1() { return cBlockParserRuleCall_1; }
		
		//Assignation
		public RuleCall getAssignationParserRuleCall_2() { return cAssignationParserRuleCall_2; }
		
		//VariableDeclaration
		public RuleCall getVariableDeclarationParserRuleCall_3() { return cVariableDeclarationParserRuleCall_3; }
		
		//FunctionCall
		public RuleCall getFunctionCallParserRuleCall_4() { return cFunctionCallParserRuleCall_4; }
		
		//Condition
		public RuleCall getConditionParserRuleCall_5() { return cConditionParserRuleCall_5; }
		
		//setSpeed
		public RuleCall getSetSpeedParserRuleCall_6() { return cSetSpeedParserRuleCall_6; }
		
		//SetClock
		public RuleCall getSetClockParserRuleCall_7() { return cSetClockParserRuleCall_7; }
		
		//Rotate
		public RuleCall getRotateParserRuleCall_8() { return cRotateParserRuleCall_8; }
		
		//Forward
		public RuleCall getForwardParserRuleCall_9() { return cForwardParserRuleCall_9; }
		
		//Backward
		public RuleCall getBackwardParserRuleCall_10() { return cBackwardParserRuleCall_10; }
		
		//Leftward
		public RuleCall getLeftwardParserRuleCall_11() { return cLeftwardParserRuleCall_11; }
		
		//Rightward
		public RuleCall getRightwardParserRuleCall_12() { return cRightwardParserRuleCall_12; }
	}
	public class VariableDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.VariableDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableDeclarationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVariableDeclarationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeTypeParserRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//VariableDeclaration returns VariableDeclaration:
		//    {VariableDeclaration}
		//    'VariableDeclaration'
		//    name=EString
		//    '{'
		//        ('type' type=Type)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{VariableDeclaration}
		//'VariableDeclaration'
		//name=EString
		//'{'
		//    ('type' type=Type)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{VariableDeclaration}
		public Action getVariableDeclarationAction_0() { return cVariableDeclarationAction_0; }
		
		//'VariableDeclaration'
		public Keyword getVariableDeclarationKeyword_1() { return cVariableDeclarationKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('type' type=Type)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=Type
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//Type
		public RuleCall getTypeTypeParserRuleCall_4_1_0() { return cTypeTypeParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class String0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.String0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStringAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStringKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//String0 returns String:
		//    {String}
		//    'String'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{String}
		//'String'
		public Group getGroup() { return cGroup; }
		
		//{String}
		public Action getStringAction_0() { return cStringAction_0; }
		
		//'String'
		public Keyword getStringKeyword_1() { return cStringKeyword_1; }
	}
	public class BooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Boolean");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBooleanAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBooleanKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Boolean returns Boolean:
		//    {Boolean}
		//    'Boolean'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Boolean}
		//'Boolean'
		public Group getGroup() { return cGroup; }
		
		//{Boolean}
		public Action getBooleanAction_0() { return cBooleanAction_0; }
		
		//'Boolean'
		public Keyword getBooleanKeyword_1() { return cBooleanKeyword_1; }
	}
	public class IntegerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Integer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntegerAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIntegerKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Integer returns Integer:
		//    {Integer}
		//    'Integer'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Integer}
		//'Integer'
		public Group getGroup() { return cGroup; }
		
		//{Integer}
		public Action getIntegerAction_0() { return cIntegerAction_0; }
		
		//'Integer'
		public Keyword getIntegerKeyword_1() { return cIntegerKeyword_1; }
	}
	public class FloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Float");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFloatAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFloatKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Float returns Float:
		//    {Float}
		//    'Float'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Float}
		//'Float'
		public Group getGroup() { return cGroup; }
		
		//{Float}
		public Action getFloatAction_0() { return cFloatAction_0; }
		
		//'Float'
		public Keyword getFloatKeyword_1() { return cFloatKeyword_1; }
	}
	public class VoidElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Void");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVoidAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVoidKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Void returns Void:
		//    {Void}
		//    'Void'
		//    ;
		@Override public ParserRule getRule() { return rule; }
		
		//{Void}
		//'Void'
		public Group getGroup() { return cGroup; }
		
		//{Void}
		public Action getVoidAction_0() { return cVoidAction_0; }
		
		//'Void'
		public Keyword getVoidKeyword_1() { return cVoidKeyword_1; }
	}
	public class FunctionCallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.FunctionCall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFunctionCallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cFunctiondeclarationKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFunctiondeclarationAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cFunctiondeclarationFunctionDeclarationCrossReference_3_0 = (CrossReference)cFunctiondeclarationAssignment_3.eContents().get(0);
		private final RuleCall cFunctiondeclarationFunctionDeclarationEStringParserRuleCall_3_0_1 = (RuleCall)cFunctiondeclarationFunctionDeclarationCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cParametersKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cParametersAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cParametersExpressionCrossReference_4_2_0 = (CrossReference)cParametersAssignment_4_2.eContents().get(0);
		private final RuleCall cParametersExpressionEStringParserRuleCall_4_2_0_1 = (RuleCall)cParametersExpressionCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cParametersAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cParametersExpressionCrossReference_4_3_1_0 = (CrossReference)cParametersAssignment_4_3_1.eContents().get(0);
		private final RuleCall cParametersExpressionEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cParametersExpressionCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cExpresionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cExpresionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cExpresionVariableDeclarationParserRuleCall_6_0 = (RuleCall)cExpresionAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//FunctionCall returns FunctionCall:
		//    'FunctionCall'
		//    '{'
		//        'functiondeclaration' functiondeclaration=[FunctionDeclaration|EString]
		//        ('parameters' '(' parameters+=[Expression|EString] ( "," parameters+=[Expression|EString])* ')' )?
		//        'expresion' expresion=VariableDeclaration
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'FunctionCall'
		//'{'
		//    'functiondeclaration' functiondeclaration=[FunctionDeclaration|EString]
		//    ('parameters' '(' parameters+=[Expression|EString] ( "," parameters+=[Expression|EString])* ')' )?
		//    'expresion' expresion=VariableDeclaration
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'FunctionCall'
		public Keyword getFunctionCallKeyword_0() { return cFunctionCallKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'functiondeclaration'
		public Keyword getFunctiondeclarationKeyword_2() { return cFunctiondeclarationKeyword_2; }
		
		//functiondeclaration=[FunctionDeclaration|EString]
		public Assignment getFunctiondeclarationAssignment_3() { return cFunctiondeclarationAssignment_3; }
		
		//[FunctionDeclaration|EString]
		public CrossReference getFunctiondeclarationFunctionDeclarationCrossReference_3_0() { return cFunctiondeclarationFunctionDeclarationCrossReference_3_0; }
		
		//EString
		public RuleCall getFunctiondeclarationFunctionDeclarationEStringParserRuleCall_3_0_1() { return cFunctiondeclarationFunctionDeclarationEStringParserRuleCall_3_0_1; }
		
		//('parameters' '(' parameters+=[Expression|EString] ( "," parameters+=[Expression|EString])* ')' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'parameters'
		public Keyword getParametersKeyword_4_0() { return cParametersKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//parameters+=[Expression|EString]
		public Assignment getParametersAssignment_4_2() { return cParametersAssignment_4_2; }
		
		//[Expression|EString]
		public CrossReference getParametersExpressionCrossReference_4_2_0() { return cParametersExpressionCrossReference_4_2_0; }
		
		//EString
		public RuleCall getParametersExpressionEStringParserRuleCall_4_2_0_1() { return cParametersExpressionEStringParserRuleCall_4_2_0_1; }
		
		//( "," parameters+=[Expression|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//parameters+=[Expression|EString]
		public Assignment getParametersAssignment_4_3_1() { return cParametersAssignment_4_3_1; }
		
		//[Expression|EString]
		public CrossReference getParametersExpressionCrossReference_4_3_1_0() { return cParametersExpressionCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getParametersExpressionEStringParserRuleCall_4_3_1_0_1() { return cParametersExpressionEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//'expresion'
		public Keyword getExpresionKeyword_5() { return cExpresionKeyword_5; }
		
		//expresion=VariableDeclaration
		public Assignment getExpresionAssignment_6() { return cExpresionAssignment_6; }
		
		//VariableDeclaration
		public RuleCall getExpresionVariableDeclarationParserRuleCall_6_0() { return cExpresionVariableDeclarationParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class BinaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Binary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBinaryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cOperatorKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cOperatorAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cOperatorBinaryOpEnumRuleCall_2_1_0 = (RuleCall)cOperatorAssignment_2_1.eContents().get(0);
		private final Keyword cExpresionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExpresionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpresionVariableDeclarationParserRuleCall_4_0 = (RuleCall)cExpresionAssignment_4.eContents().get(0);
		private final Keyword cExpressionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cExpressionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cExpressionExpressionParserRuleCall_7_0 = (RuleCall)cExpressionAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cExpressionAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cExpressionExpressionParserRuleCall_8_1_0 = (RuleCall)cExpressionAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cOperandsKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cLeftCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cOperandsAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cOperandsExpressionParserRuleCall_12_0 = (RuleCall)cOperandsAssignment_12.eContents().get(0);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cCommaKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cOperandsAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final RuleCall cOperandsExpressionParserRuleCall_13_1_0 = (RuleCall)cOperandsAssignment_13_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Binary returns Binary:
		//    'Binary'
		//    '{'
		//        ('Operator' Operator=BinaryOp)?
		//        'expresion' expresion=VariableDeclaration
		//        'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
		//        'operands' '{' operands+=Expression ( "," operands+=Expression)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Binary'
		//'{'
		//    ('Operator' Operator=BinaryOp)?
		//    'expresion' expresion=VariableDeclaration
		//    'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
		//    'operands' '{' operands+=Expression ( "," operands+=Expression)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Binary'
		public Keyword getBinaryKeyword_0() { return cBinaryKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('Operator' Operator=BinaryOp)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'Operator'
		public Keyword getOperatorKeyword_2_0() { return cOperatorKeyword_2_0; }
		
		//Operator=BinaryOp
		public Assignment getOperatorAssignment_2_1() { return cOperatorAssignment_2_1; }
		
		//BinaryOp
		public RuleCall getOperatorBinaryOpEnumRuleCall_2_1_0() { return cOperatorBinaryOpEnumRuleCall_2_1_0; }
		
		//'expresion'
		public Keyword getExpresionKeyword_3() { return cExpresionKeyword_3; }
		
		//expresion=VariableDeclaration
		public Assignment getExpresionAssignment_4() { return cExpresionAssignment_4; }
		
		//VariableDeclaration
		public RuleCall getExpresionVariableDeclarationParserRuleCall_4_0() { return cExpresionVariableDeclarationParserRuleCall_4_0; }
		
		//'expression'
		public Keyword getExpressionKeyword_5() { return cExpressionKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//expression+=Expression
		public Assignment getExpressionAssignment_7() { return cExpressionAssignment_7; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_7_0() { return cExpressionExpressionParserRuleCall_7_0; }
		
		//( "," expression+=Expression)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//expression+=Expression
		public Assignment getExpressionAssignment_8_1() { return cExpressionAssignment_8_1; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_8_1_0() { return cExpressionExpressionParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'operands'
		public Keyword getOperandsKeyword_10() { return cOperandsKeyword_10; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_11() { return cLeftCurlyBracketKeyword_11; }
		
		//operands+=Expression
		public Assignment getOperandsAssignment_12() { return cOperandsAssignment_12; }
		
		//Expression
		public RuleCall getOperandsExpressionParserRuleCall_12_0() { return cOperandsExpressionParserRuleCall_12_0; }
		
		//( "," operands+=Expression)*
		public Group getGroup_13() { return cGroup_13; }
		
		//","
		public Keyword getCommaKeyword_13_0() { return cCommaKeyword_13_0; }
		
		//operands+=Expression
		public Assignment getOperandsAssignment_13_1() { return cOperandsAssignment_13_1; }
		
		//Expression
		public RuleCall getOperandsExpressionParserRuleCall_13_1_0() { return cOperandsExpressionParserRuleCall_13_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}
	public class UnaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Unary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUnaryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cOperatorKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cOperatorAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cOperatorUnaryOpEnumRuleCall_2_1_0 = (RuleCall)cOperatorAssignment_2_1.eContents().get(0);
		private final Keyword cExpresionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExpresionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpresionVariableDeclarationParserRuleCall_4_0 = (RuleCall)cExpresionAssignment_4.eContents().get(0);
		private final Keyword cExpressionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cExpressionAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cExpressionExpressionParserRuleCall_7_0 = (RuleCall)cExpressionAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cExpressionAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cExpressionExpressionParserRuleCall_8_1_0 = (RuleCall)cExpressionAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cOperandKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cOperandAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cOperandExpressionParserRuleCall_11_0 = (RuleCall)cOperandAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Unary returns Unary:
		//    'Unary'
		//    '{'
		//        ('Operator' Operator=UnaryOp)?
		//        'expresion' expresion=VariableDeclaration
		//        'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
		//        'operand' operand=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Unary'
		//'{'
		//    ('Operator' Operator=UnaryOp)?
		//    'expresion' expresion=VariableDeclaration
		//    'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
		//    'operand' operand=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Unary'
		public Keyword getUnaryKeyword_0() { return cUnaryKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('Operator' Operator=UnaryOp)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'Operator'
		public Keyword getOperatorKeyword_2_0() { return cOperatorKeyword_2_0; }
		
		//Operator=UnaryOp
		public Assignment getOperatorAssignment_2_1() { return cOperatorAssignment_2_1; }
		
		//UnaryOp
		public RuleCall getOperatorUnaryOpEnumRuleCall_2_1_0() { return cOperatorUnaryOpEnumRuleCall_2_1_0; }
		
		//'expresion'
		public Keyword getExpresionKeyword_3() { return cExpresionKeyword_3; }
		
		//expresion=VariableDeclaration
		public Assignment getExpresionAssignment_4() { return cExpresionAssignment_4; }
		
		//VariableDeclaration
		public RuleCall getExpresionVariableDeclarationParserRuleCall_4_0() { return cExpresionVariableDeclarationParserRuleCall_4_0; }
		
		//'expression'
		public Keyword getExpressionKeyword_5() { return cExpressionKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//expression+=Expression
		public Assignment getExpressionAssignment_7() { return cExpressionAssignment_7; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_7_0() { return cExpressionExpressionParserRuleCall_7_0; }
		
		//( "," expression+=Expression)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//expression+=Expression
		public Assignment getExpressionAssignment_8_1() { return cExpressionAssignment_8_1; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_8_1_0() { return cExpressionExpressionParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'operand'
		public Keyword getOperandKeyword_10() { return cOperandKeyword_10; }
		
		//operand=Expression
		public Assignment getOperandAssignment_11() { return cOperandAssignment_11; }
		
		//Expression
		public RuleCall getOperandExpressionParserRuleCall_11_0() { return cOperandExpressionParserRuleCall_11_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class VariableRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.VariableRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVariableRefKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cRefKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRefAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cRefVariableDeclarationCrossReference_3_0 = (CrossReference)cRefAssignment_3.eContents().get(0);
		private final RuleCall cRefVariableDeclarationEStringParserRuleCall_3_0_1 = (RuleCall)cRefVariableDeclarationCrossReference_3_0.eContents().get(1);
		private final Keyword cExpresionKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cExpresionAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cExpresionVariableDeclarationParserRuleCall_5_0 = (RuleCall)cExpresionAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//VariableRef returns VariableRef:
		//    'VariableRef'
		//    '{'
		//        'ref' ref=[VariableDeclaration|EString]
		//        'expresion' expresion=VariableDeclaration
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'VariableRef'
		//'{'
		//    'ref' ref=[VariableDeclaration|EString]
		//    'expresion' expresion=VariableDeclaration
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'VariableRef'
		public Keyword getVariableRefKeyword_0() { return cVariableRefKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'ref'
		public Keyword getRefKeyword_2() { return cRefKeyword_2; }
		
		//ref=[VariableDeclaration|EString]
		public Assignment getRefAssignment_3() { return cRefAssignment_3; }
		
		//[VariableDeclaration|EString]
		public CrossReference getRefVariableDeclarationCrossReference_3_0() { return cRefVariableDeclarationCrossReference_3_0; }
		
		//EString
		public RuleCall getRefVariableDeclarationEStringParserRuleCall_3_0_1() { return cRefVariableDeclarationEStringParserRuleCall_3_0_1; }
		
		//'expresion'
		public Keyword getExpresionKeyword_4() { return cExpresionKeyword_4; }
		
		//expresion=VariableDeclaration
		public Assignment getExpresionAssignment_5() { return cExpresionAssignment_5; }
		
		//VariableDeclaration
		public RuleCall getExpresionVariableDeclarationParserRuleCall_5_0() { return cExpresionVariableDeclarationParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class GetSpeedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.GetSpeed");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGetSpeedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExpresionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpresionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpresionVariableDeclarationParserRuleCall_3_0 = (RuleCall)cExpresionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//GetSpeed returns GetSpeed:
		//    'GetSpeed'
		//    '{'
		//        'expresion' expresion=VariableDeclaration
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'GetSpeed'
		//'{'
		//    'expresion' expresion=VariableDeclaration
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'GetSpeed'
		public Keyword getGetSpeedKeyword_0() { return cGetSpeedKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'expresion'
		public Keyword getExpresionKeyword_2() { return cExpresionKeyword_2; }
		
		//expresion=VariableDeclaration
		public Assignment getExpresionAssignment_3() { return cExpresionAssignment_3; }
		
		//VariableDeclaration
		public RuleCall getExpresionVariableDeclarationParserRuleCall_3_0() { return cExpresionVariableDeclarationParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class GetClockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.GetClock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGetClockKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExpresionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpresionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpresionVariableDeclarationParserRuleCall_3_0 = (RuleCall)cExpresionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//GetClock returns GetClock:
		//    'GetClock'
		//    '{'
		//        'expresion' expresion=VariableDeclaration
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'GetClock'
		//'{'
		//    'expresion' expresion=VariableDeclaration
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'GetClock'
		public Keyword getGetClockKeyword_0() { return cGetClockKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'expresion'
		public Keyword getExpresionKeyword_2() { return cExpresionKeyword_2; }
		
		//expresion=VariableDeclaration
		public Assignment getExpresionAssignment_3() { return cExpresionAssignment_3; }
		
		//VariableDeclaration
		public RuleCall getExpresionVariableDeclarationParserRuleCall_3_0() { return cExpresionVariableDeclarationParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class GetSensorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.GetSensor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGetSensorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cSensorKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSensorAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cSensorSensorEnumRuleCall_2_1_0 = (RuleCall)cSensorAssignment_2_1.eContents().get(0);
		private final Keyword cExpresionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cExpresionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cExpresionVariableDeclarationParserRuleCall_4_0 = (RuleCall)cExpresionAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//GetSensor returns GetSensor:
		//    'GetSensor'
		//    '{'
		//        ('sensor' sensor=Sensor)?
		//        'expresion' expresion=VariableDeclaration
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'GetSensor'
		//'{'
		//    ('sensor' sensor=Sensor)?
		//    'expresion' expresion=VariableDeclaration
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'GetSensor'
		public Keyword getGetSensorKeyword_0() { return cGetSensorKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('sensor' sensor=Sensor)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'sensor'
		public Keyword getSensorKeyword_2_0() { return cSensorKeyword_2_0; }
		
		//sensor=Sensor
		public Assignment getSensorAssignment_2_1() { return cSensorAssignment_2_1; }
		
		//Sensor
		public RuleCall getSensorSensorEnumRuleCall_2_1_0() { return cSensorSensorEnumRuleCall_2_1_0; }
		
		//'expresion'
		public Keyword getExpresionKeyword_3() { return cExpresionKeyword_3; }
		
		//expresion=VariableDeclaration
		public Assignment getExpresionAssignment_4() { return cExpresionAssignment_4; }
		
		//VariableDeclaration
		public RuleCall getExpresionVariableDeclarationParserRuleCall_4_0() { return cExpresionVariableDeclarationParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class FunctionDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.FunctionDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFunctionDeclarationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cReturnTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cReturnTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cReturnTypeTypeParserRuleCall_3_0 = (RuleCall)cReturnTypeAssignment_3.eContents().get(0);
		private final Keyword cBlockKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBlockAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBlockBlockParserRuleCall_5_0 = (RuleCall)cBlockAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cParametersKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cParametersAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cParametersVariableDeclarationParserRuleCall_6_2_0 = (RuleCall)cParametersAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cParametersAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cParametersVariableDeclarationParserRuleCall_6_3_1_0 = (RuleCall)cParametersAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//FunctionDeclaration returns FunctionDeclaration:
		//    'FunctionDeclaration'
		//    '{'
		//        'returnType' returnType=Type
		//        'block' block=Block
		//        ('parameters' '{' parameters+=VariableDeclaration ( "," parameters+=VariableDeclaration)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'FunctionDeclaration'
		//'{'
		//    'returnType' returnType=Type
		//    'block' block=Block
		//    ('parameters' '{' parameters+=VariableDeclaration ( "," parameters+=VariableDeclaration)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'FunctionDeclaration'
		public Keyword getFunctionDeclarationKeyword_0() { return cFunctionDeclarationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'returnType'
		public Keyword getReturnTypeKeyword_2() { return cReturnTypeKeyword_2; }
		
		//returnType=Type
		public Assignment getReturnTypeAssignment_3() { return cReturnTypeAssignment_3; }
		
		//Type
		public RuleCall getReturnTypeTypeParserRuleCall_3_0() { return cReturnTypeTypeParserRuleCall_3_0; }
		
		//'block'
		public Keyword getBlockKeyword_4() { return cBlockKeyword_4; }
		
		//block=Block
		public Assignment getBlockAssignment_5() { return cBlockAssignment_5; }
		
		//Block
		public RuleCall getBlockBlockParserRuleCall_5_0() { return cBlockBlockParserRuleCall_5_0; }
		
		//('parameters' '{' parameters+=VariableDeclaration ( "," parameters+=VariableDeclaration)* '}' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'parameters'
		public Keyword getParametersKeyword_6_0() { return cParametersKeyword_6_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }
		
		//parameters+=VariableDeclaration
		public Assignment getParametersAssignment_6_2() { return cParametersAssignment_6_2; }
		
		//VariableDeclaration
		public RuleCall getParametersVariableDeclarationParserRuleCall_6_2_0() { return cParametersVariableDeclarationParserRuleCall_6_2_0; }
		
		//( "," parameters+=VariableDeclaration)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//parameters+=VariableDeclaration
		public Assignment getParametersAssignment_6_3_1() { return cParametersAssignment_6_3_1; }
		
		//VariableDeclaration
		public RuleCall getParametersVariableDeclarationParserRuleCall_6_3_1_0() { return cParametersVariableDeclarationParserRuleCall_6_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class BlockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Block");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBlockAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBlockKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cStatementsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cStatementsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cStatementsStatementParserRuleCall_3_2_0 = (RuleCall)cStatementsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cStatementsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cStatementsStatementParserRuleCall_3_3_1_0 = (RuleCall)cStatementsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Block returns Block:
		//    {Block}
		//    'Block'
		//    '{'
		//        ('statements' '{' statements+=Statement ( "," statements+=Statement)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Block}
		//'Block'
		//'{'
		//    ('statements' '{' statements+=Statement ( "," statements+=Statement)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Block}
		public Action getBlockAction_0() { return cBlockAction_0; }
		
		//'Block'
		public Keyword getBlockKeyword_1() { return cBlockKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('statements' '{' statements+=Statement ( "," statements+=Statement)* '}' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'statements'
		public Keyword getStatementsKeyword_3_0() { return cStatementsKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//statements+=Statement
		public Assignment getStatementsAssignment_3_2() { return cStatementsAssignment_3_2; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_3_2_0() { return cStatementsStatementParserRuleCall_3_2_0; }
		
		//( "," statements+=Statement)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//statements+=Statement
		public Assignment getStatementsAssignment_3_3_1() { return cStatementsAssignment_3_3_1; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_3_3_1_0() { return cStatementsStatementParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Condition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConditionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cBlockKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cBlockAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cBlockBlockParserRuleCall_4_0 = (RuleCall)cBlockAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cBlockAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cBlockBlockParserRuleCall_5_1_0 = (RuleCall)cBlockAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cConditionsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cConditionsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cConditionsExpressionParserRuleCall_9_0 = (RuleCall)cConditionsAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cConditionsAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cConditionsExpressionParserRuleCall_10_1_0 = (RuleCall)cConditionsAssignment_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Condition returns Condition:
		//    'Condition'
		//    '{'
		//        'block' '{' block+=Block ( "," block+=Block)* '}'
		//        'conditions' '{' conditions+=Expression ( "," conditions+=Expression)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Condition'
		//'{'
		//    'block' '{' block+=Block ( "," block+=Block)* '}'
		//    'conditions' '{' conditions+=Expression ( "," conditions+=Expression)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Condition'
		public Keyword getConditionKeyword_0() { return cConditionKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'block'
		public Keyword getBlockKeyword_2() { return cBlockKeyword_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//block+=Block
		public Assignment getBlockAssignment_4() { return cBlockAssignment_4; }
		
		//Block
		public RuleCall getBlockBlockParserRuleCall_4_0() { return cBlockBlockParserRuleCall_4_0; }
		
		//( "," block+=Block)*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//block+=Block
		public Assignment getBlockAssignment_5_1() { return cBlockAssignment_5_1; }
		
		//Block
		public RuleCall getBlockBlockParserRuleCall_5_1_0() { return cBlockBlockParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
		
		//'conditions'
		public Keyword getConditionsKeyword_7() { return cConditionsKeyword_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8() { return cLeftCurlyBracketKeyword_8; }
		
		//conditions+=Expression
		public Assignment getConditionsAssignment_9() { return cConditionsAssignment_9; }
		
		//Expression
		public RuleCall getConditionsExpressionParserRuleCall_9_0() { return cConditionsExpressionParserRuleCall_9_0; }
		
		//( "," conditions+=Expression)*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//conditions+=Expression
		public Assignment getConditionsAssignment_10_1() { return cConditionsAssignment_10_1; }
		
		//Expression
		public RuleCall getConditionsExpressionParserRuleCall_10_1_0() { return cConditionsExpressionParserRuleCall_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class SetSpeedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.setSpeed");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSetSpeedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExpressionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//setSpeed returns setSpeed:
		//    'setSpeed'
		//    '{'
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'setSpeed'
		//'{'
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'setSpeed'
		public Keyword getSetSpeedKeyword_0() { return cSetSpeedKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'expression'
		public Keyword getExpressionKeyword_2() { return cExpressionKeyword_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_3_0() { return cExpressionExpressionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class SetClockElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.SetClock");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSetClockKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExpressionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SetClock returns SetClock:
		//    'SetClock'
		//    '{'
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'SetClock'
		//'{'
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'SetClock'
		public Keyword getSetClockKeyword_0() { return cSetClockKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'expression'
		public Keyword getExpressionKeyword_2() { return cExpressionKeyword_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_3_0() { return cExpressionExpressionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class RotateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Rotate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRotateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExpressionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Rotate returns Rotate:
		//    'Rotate'
		//    '{'
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Rotate'
		//'{'
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Rotate'
		public Keyword getRotateKeyword_0() { return cRotateKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'expression'
		public Keyword getExpressionKeyword_2() { return cExpressionKeyword_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_3_0() { return cExpressionExpressionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ForwardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Forward");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cForwardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExpressionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Forward returns Forward:
		//    'Forward'
		//    '{'
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Forward'
		//'{'
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Forward'
		public Keyword getForwardKeyword_0() { return cForwardKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'expression'
		public Keyword getExpressionKeyword_2() { return cExpressionKeyword_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_3_0() { return cExpressionExpressionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class BackwardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Backward");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBackwardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExpressionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Backward returns Backward:
		//    'Backward'
		//    '{'
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Backward'
		//'{'
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Backward'
		public Keyword getBackwardKeyword_0() { return cBackwardKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'expression'
		public Keyword getExpressionKeyword_2() { return cExpressionKeyword_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_3_0() { return cExpressionExpressionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class LeftwardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Leftward");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftwardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExpressionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Leftward returns Leftward:
		//    'Leftward'
		//    '{'
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Leftward'
		//'{'
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Leftward'
		public Keyword getLeftwardKeyword_0() { return cLeftwardKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'expression'
		public Keyword getExpressionKeyword_2() { return cExpressionKeyword_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_3_0() { return cExpressionExpressionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class RightwardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Rightward");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRightwardKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cExpressionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cExpressionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cExpressionExpressionParserRuleCall_3_0 = (RuleCall)cExpressionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Rightward returns Rightward:
		//    'Rightward'
		//    '{'
		//        'expression' expression=Expression
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Rightward'
		//'{'
		//    'expression' expression=Expression
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Rightward'
		public Keyword getRightwardKeyword_0() { return cRightwardKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'expression'
		public Keyword getExpressionKeyword_2() { return cExpressionKeyword_2; }
		
		//expression=Expression
		public Assignment getExpressionAssignment_3() { return cExpressionAssignment_3; }
		
		//Expression
		public RuleCall getExpressionExpressionParserRuleCall_3_0() { return cExpressionExpressionParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	public class BinaryOpElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.BinaryOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cANDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cANDANDKeyword_0_0 = (Keyword)cANDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cOREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cORORKeyword_1_0 = (Keyword)cOREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cNOTEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cNOTNOTKeyword_2_0 = (Keyword)cNOTEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cEQUALEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cEQUALEQUALKeyword_3_0 = (Keyword)cEQUALEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cLESSOREQUALEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cLESSOREQUALLESSOREQUALKeyword_4_0 = (Keyword)cLESSOREQUALEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cGREATEROREQUALEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cGREATEROREQUALGREATEROREQUALKeyword_5_0 = (Keyword)cGREATEROREQUALEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cLESSEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cLESSLESSKeyword_6_0 = (Keyword)cLESSEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cGREATEREnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cGREATERGREATERKeyword_7_0 = (Keyword)cGREATEREnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cPLUSEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cPLUSPLUSKeyword_8_0 = (Keyword)cPLUSEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cMINUSEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cMINUSMINUSKeyword_9_0 = (Keyword)cMINUSEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cTIMESEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cTIMESTIMESKeyword_10_0 = (Keyword)cTIMESEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cDIVIDEEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cDIVIDEDIVIDEKeyword_11_0 = (Keyword)cDIVIDEEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cMODULOEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cMODULOMODULOKeyword_12_0 = (Keyword)cMODULOEnumLiteralDeclaration_12.eContents().get(0);
		
		//enum BinaryOp returns BinaryOp:
		//                AND = 'AND' | OR = 'OR' | NOT = 'NOT' | EQUAL = 'EQUAL' | LESSOREQUAL = 'LESSOREQUAL' | GREATEROREQUAL = 'GREATEROREQUAL' | LESS = 'LESS' | GREATER = 'GREATER' | PLUS = 'PLUS' | MINUS = 'MINUS' | TIMES = 'TIMES' | DIVIDE = 'DIVIDE' | MODULO = 'MODULO';
		public EnumRule getRule() { return rule; }
		
		//AND = 'AND' | OR = 'OR' | NOT = 'NOT' | EQUAL = 'EQUAL' | LESSOREQUAL = 'LESSOREQUAL' | GREATEROREQUAL = 'GREATEROREQUAL' | LESS = 'LESS' | GREATER = 'GREATER' | PLUS = 'PLUS' | MINUS = 'MINUS' | TIMES = 'TIMES' | DIVIDE = 'DIVIDE' | MODULO = 'MODULO'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AND = 'AND'
		public EnumLiteralDeclaration getANDEnumLiteralDeclaration_0() { return cANDEnumLiteralDeclaration_0; }
		
		//'AND'
		public Keyword getANDANDKeyword_0_0() { return cANDANDKeyword_0_0; }
		
		//OR = 'OR'
		public EnumLiteralDeclaration getOREnumLiteralDeclaration_1() { return cOREnumLiteralDeclaration_1; }
		
		//'OR'
		public Keyword getORORKeyword_1_0() { return cORORKeyword_1_0; }
		
		//NOT = 'NOT'
		public EnumLiteralDeclaration getNOTEnumLiteralDeclaration_2() { return cNOTEnumLiteralDeclaration_2; }
		
		//'NOT'
		public Keyword getNOTNOTKeyword_2_0() { return cNOTNOTKeyword_2_0; }
		
		//EQUAL = 'EQUAL'
		public EnumLiteralDeclaration getEQUALEnumLiteralDeclaration_3() { return cEQUALEnumLiteralDeclaration_3; }
		
		//'EQUAL'
		public Keyword getEQUALEQUALKeyword_3_0() { return cEQUALEQUALKeyword_3_0; }
		
		//LESSOREQUAL = 'LESSOREQUAL'
		public EnumLiteralDeclaration getLESSOREQUALEnumLiteralDeclaration_4() { return cLESSOREQUALEnumLiteralDeclaration_4; }
		
		//'LESSOREQUAL'
		public Keyword getLESSOREQUALLESSOREQUALKeyword_4_0() { return cLESSOREQUALLESSOREQUALKeyword_4_0; }
		
		//GREATEROREQUAL = 'GREATEROREQUAL'
		public EnumLiteralDeclaration getGREATEROREQUALEnumLiteralDeclaration_5() { return cGREATEROREQUALEnumLiteralDeclaration_5; }
		
		//'GREATEROREQUAL'
		public Keyword getGREATEROREQUALGREATEROREQUALKeyword_5_0() { return cGREATEROREQUALGREATEROREQUALKeyword_5_0; }
		
		//LESS = 'LESS'
		public EnumLiteralDeclaration getLESSEnumLiteralDeclaration_6() { return cLESSEnumLiteralDeclaration_6; }
		
		//'LESS'
		public Keyword getLESSLESSKeyword_6_0() { return cLESSLESSKeyword_6_0; }
		
		//GREATER = 'GREATER'
		public EnumLiteralDeclaration getGREATEREnumLiteralDeclaration_7() { return cGREATEREnumLiteralDeclaration_7; }
		
		//'GREATER'
		public Keyword getGREATERGREATERKeyword_7_0() { return cGREATERGREATERKeyword_7_0; }
		
		//PLUS = 'PLUS'
		public EnumLiteralDeclaration getPLUSEnumLiteralDeclaration_8() { return cPLUSEnumLiteralDeclaration_8; }
		
		//'PLUS'
		public Keyword getPLUSPLUSKeyword_8_0() { return cPLUSPLUSKeyword_8_0; }
		
		//MINUS = 'MINUS'
		public EnumLiteralDeclaration getMINUSEnumLiteralDeclaration_9() { return cMINUSEnumLiteralDeclaration_9; }
		
		//'MINUS'
		public Keyword getMINUSMINUSKeyword_9_0() { return cMINUSMINUSKeyword_9_0; }
		
		//TIMES = 'TIMES'
		public EnumLiteralDeclaration getTIMESEnumLiteralDeclaration_10() { return cTIMESEnumLiteralDeclaration_10; }
		
		//'TIMES'
		public Keyword getTIMESTIMESKeyword_10_0() { return cTIMESTIMESKeyword_10_0; }
		
		//DIVIDE = 'DIVIDE'
		public EnumLiteralDeclaration getDIVIDEEnumLiteralDeclaration_11() { return cDIVIDEEnumLiteralDeclaration_11; }
		
		//'DIVIDE'
		public Keyword getDIVIDEDIVIDEKeyword_11_0() { return cDIVIDEDIVIDEKeyword_11_0; }
		
		//MODULO = 'MODULO'
		public EnumLiteralDeclaration getMODULOEnumLiteralDeclaration_12() { return cMODULOEnumLiteralDeclaration_12; }
		
		//'MODULO'
		public Keyword getMODULOMODULOKeyword_12_0() { return cMODULOMODULOKeyword_12_0; }
	}
	public class UnaryOpElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.UnaryOp");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cNOTEQUALEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cNOTEQUALNOTEQUALKeyword_0_0 = (Keyword)cNOTEQUALEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNEGATEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNEGATENEGATEKeyword_1_0 = (Keyword)cNEGATEEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum UnaryOp returns UnaryOp:
		//                NOTEQUAL = 'NOTEQUAL' | NEGATE = 'NEGATE';
		public EnumRule getRule() { return rule; }
		
		//NOTEQUAL = 'NOTEQUAL' | NEGATE = 'NEGATE'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//NOTEQUAL = 'NOTEQUAL'
		public EnumLiteralDeclaration getNOTEQUALEnumLiteralDeclaration_0() { return cNOTEQUALEnumLiteralDeclaration_0; }
		
		//'NOTEQUAL'
		public Keyword getNOTEQUALNOTEQUALKeyword_0_0() { return cNOTEQUALNOTEQUALKeyword_0_0; }
		
		//NEGATE = 'NEGATE'
		public EnumLiteralDeclaration getNEGATEEnumLiteralDeclaration_1() { return cNEGATEEnumLiteralDeclaration_1; }
		
		//'NEGATE'
		public Keyword getNEGATENEGATEKeyword_1_0() { return cNEGATENEGATEKeyword_1_0; }
	}
	public class SensorElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.robotml.RobotML.Sensor");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDistanceEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDistanceDistanceKeyword_0_0 = (Keyword)cDistanceEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cColorEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cColorColorKeyword_1_0 = (Keyword)cColorEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Sensor returns Sensor:
		//                Distance = 'Distance' | Color = 'Color';
		public EnumRule getRule() { return rule; }
		
		//Distance = 'Distance' | Color = 'Color'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Distance = 'Distance'
		public EnumLiteralDeclaration getDistanceEnumLiteralDeclaration_0() { return cDistanceEnumLiteralDeclaration_0; }
		
		//'Distance'
		public Keyword getDistanceDistanceKeyword_0_0() { return cDistanceDistanceKeyword_0_0; }
		
		//Color = 'Color'
		public EnumLiteralDeclaration getColorEnumLiteralDeclaration_1() { return cColorEnumLiteralDeclaration_1; }
		
		//'Color'
		public Keyword getColorColorKeyword_1_0() { return cColorColorKeyword_1_0; }
	}
	
	private final AssignationElements pAssignation;
	private final ExpressionElements pExpression;
	private final TypeElements pType;
	private final StatementElements pStatement;
	private final VariableDeclarationElements pVariableDeclaration;
	private final EStringElements pEString;
	private final String0Elements pString0;
	private final BooleanElements pBoolean;
	private final IntegerElements pInteger;
	private final FloatElements pFloat;
	private final VoidElements pVoid;
	private final FunctionCallElements pFunctionCall;
	private final BinaryElements pBinary;
	private final UnaryElements pUnary;
	private final VariableRefElements pVariableRef;
	private final GetSpeedElements pGetSpeed;
	private final GetClockElements pGetClock;
	private final GetSensorElements pGetSensor;
	private final FunctionDeclarationElements pFunctionDeclaration;
	private final BlockElements pBlock;
	private final ConditionElements pCondition;
	private final SetSpeedElements pSetSpeed;
	private final SetClockElements pSetClock;
	private final RotateElements pRotate;
	private final ForwardElements pForward;
	private final BackwardElements pBackward;
	private final LeftwardElements pLeftward;
	private final RightwardElements pRightward;
	private final BinaryOpElements eBinaryOp;
	private final UnaryOpElements eUnaryOp;
	private final SensorElements eSensor;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RobotMLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pAssignation = new AssignationElements();
		this.pExpression = new ExpressionElements();
		this.pType = new TypeElements();
		this.pStatement = new StatementElements();
		this.pVariableDeclaration = new VariableDeclarationElements();
		this.pEString = new EStringElements();
		this.pString0 = new String0Elements();
		this.pBoolean = new BooleanElements();
		this.pInteger = new IntegerElements();
		this.pFloat = new FloatElements();
		this.pVoid = new VoidElements();
		this.pFunctionCall = new FunctionCallElements();
		this.pBinary = new BinaryElements();
		this.pUnary = new UnaryElements();
		this.pVariableRef = new VariableRefElements();
		this.pGetSpeed = new GetSpeedElements();
		this.pGetClock = new GetClockElements();
		this.pGetSensor = new GetSensorElements();
		this.pFunctionDeclaration = new FunctionDeclarationElements();
		this.pBlock = new BlockElements();
		this.pCondition = new ConditionElements();
		this.pSetSpeed = new SetSpeedElements();
		this.pSetClock = new SetClockElements();
		this.pRotate = new RotateElements();
		this.pForward = new ForwardElements();
		this.pBackward = new BackwardElements();
		this.pLeftward = new LeftwardElements();
		this.pRightward = new RightwardElements();
		this.eBinaryOp = new BinaryOpElements();
		this.eUnaryOp = new UnaryOpElements();
		this.eSensor = new SensorElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.robotml.RobotML".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Assignation returns Assignation:
	//    'Assignation'
	//    '{'
	//        'variableDecl' variableDecl=VariableDeclaration
	//        'expression' expression=Expression
	//    '}';
	public AssignationElements getAssignationAccess() {
		return pAssignation;
	}
	
	public ParserRule getAssignationRule() {
		return getAssignationAccess().getRule();
	}
	
	//Expression returns Expression:
	//    FunctionCall | Binary | Unary | VariableRef | GetSpeed | GetClock | GetSensor;
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Type returns Type:
	//    String0 | Boolean | Integer | Float | Void;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Statement returns Statement:
	//    FunctionDeclaration | Block | Assignation | VariableDeclaration | FunctionCall | Condition | setSpeed | SetClock | Rotate | Forward | Backward | Leftward | Rightward;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//VariableDeclaration returns VariableDeclaration:
	//    {VariableDeclaration}
	//    'VariableDeclaration'
	//    name=EString
	//    '{'
	//        ('type' type=Type)?
	//    '}';
	public VariableDeclarationElements getVariableDeclarationAccess() {
		return pVariableDeclaration;
	}
	
	public ParserRule getVariableDeclarationRule() {
		return getVariableDeclarationAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//String0 returns String:
	//    {String}
	//    'String'
	//    ;
	public String0Elements getString0Access() {
		return pString0;
	}
	
	public ParserRule getString0Rule() {
		return getString0Access().getRule();
	}
	
	//Boolean returns Boolean:
	//    {Boolean}
	//    'Boolean'
	//    ;
	public BooleanElements getBooleanAccess() {
		return pBoolean;
	}
	
	public ParserRule getBooleanRule() {
		return getBooleanAccess().getRule();
	}
	
	//Integer returns Integer:
	//    {Integer}
	//    'Integer'
	//    ;
	public IntegerElements getIntegerAccess() {
		return pInteger;
	}
	
	public ParserRule getIntegerRule() {
		return getIntegerAccess().getRule();
	}
	
	//Float returns Float:
	//    {Float}
	//    'Float'
	//    ;
	public FloatElements getFloatAccess() {
		return pFloat;
	}
	
	public ParserRule getFloatRule() {
		return getFloatAccess().getRule();
	}
	
	//Void returns Void:
	//    {Void}
	//    'Void'
	//    ;
	public VoidElements getVoidAccess() {
		return pVoid;
	}
	
	public ParserRule getVoidRule() {
		return getVoidAccess().getRule();
	}
	
	//FunctionCall returns FunctionCall:
	//    'FunctionCall'
	//    '{'
	//        'functiondeclaration' functiondeclaration=[FunctionDeclaration|EString]
	//        ('parameters' '(' parameters+=[Expression|EString] ( "," parameters+=[Expression|EString])* ')' )?
	//        'expresion' expresion=VariableDeclaration
	//    '}';
	public FunctionCallElements getFunctionCallAccess() {
		return pFunctionCall;
	}
	
	public ParserRule getFunctionCallRule() {
		return getFunctionCallAccess().getRule();
	}
	
	//Binary returns Binary:
	//    'Binary'
	//    '{'
	//        ('Operator' Operator=BinaryOp)?
	//        'expresion' expresion=VariableDeclaration
	//        'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
	//        'operands' '{' operands+=Expression ( "," operands+=Expression)* '}'
	//    '}';
	public BinaryElements getBinaryAccess() {
		return pBinary;
	}
	
	public ParserRule getBinaryRule() {
		return getBinaryAccess().getRule();
	}
	
	//Unary returns Unary:
	//    'Unary'
	//    '{'
	//        ('Operator' Operator=UnaryOp)?
	//        'expresion' expresion=VariableDeclaration
	//        'expression' '{' expression+=Expression ( "," expression+=Expression)* '}'
	//        'operand' operand=Expression
	//    '}';
	public UnaryElements getUnaryAccess() {
		return pUnary;
	}
	
	public ParserRule getUnaryRule() {
		return getUnaryAccess().getRule();
	}
	
	//VariableRef returns VariableRef:
	//    'VariableRef'
	//    '{'
	//        'ref' ref=[VariableDeclaration|EString]
	//        'expresion' expresion=VariableDeclaration
	//    '}';
	public VariableRefElements getVariableRefAccess() {
		return pVariableRef;
	}
	
	public ParserRule getVariableRefRule() {
		return getVariableRefAccess().getRule();
	}
	
	//GetSpeed returns GetSpeed:
	//    'GetSpeed'
	//    '{'
	//        'expresion' expresion=VariableDeclaration
	//    '}';
	public GetSpeedElements getGetSpeedAccess() {
		return pGetSpeed;
	}
	
	public ParserRule getGetSpeedRule() {
		return getGetSpeedAccess().getRule();
	}
	
	//GetClock returns GetClock:
	//    'GetClock'
	//    '{'
	//        'expresion' expresion=VariableDeclaration
	//    '}';
	public GetClockElements getGetClockAccess() {
		return pGetClock;
	}
	
	public ParserRule getGetClockRule() {
		return getGetClockAccess().getRule();
	}
	
	//GetSensor returns GetSensor:
	//    'GetSensor'
	//    '{'
	//        ('sensor' sensor=Sensor)?
	//        'expresion' expresion=VariableDeclaration
	//    '}';
	public GetSensorElements getGetSensorAccess() {
		return pGetSensor;
	}
	
	public ParserRule getGetSensorRule() {
		return getGetSensorAccess().getRule();
	}
	
	//FunctionDeclaration returns FunctionDeclaration:
	//    'FunctionDeclaration'
	//    '{'
	//        'returnType' returnType=Type
	//        'block' block=Block
	//        ('parameters' '{' parameters+=VariableDeclaration ( "," parameters+=VariableDeclaration)* '}' )?
	//    '}';
	public FunctionDeclarationElements getFunctionDeclarationAccess() {
		return pFunctionDeclaration;
	}
	
	public ParserRule getFunctionDeclarationRule() {
		return getFunctionDeclarationAccess().getRule();
	}
	
	//Block returns Block:
	//    {Block}
	//    'Block'
	//    '{'
	//        ('statements' '{' statements+=Statement ( "," statements+=Statement)* '}' )?
	//    '}';
	public BlockElements getBlockAccess() {
		return pBlock;
	}
	
	public ParserRule getBlockRule() {
		return getBlockAccess().getRule();
	}
	
	//Condition returns Condition:
	//    'Condition'
	//    '{'
	//        'block' '{' block+=Block ( "," block+=Block)* '}'
	//        'conditions' '{' conditions+=Expression ( "," conditions+=Expression)* '}'
	//    '}';
	public ConditionElements getConditionAccess() {
		return pCondition;
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}
	
	//setSpeed returns setSpeed:
	//    'setSpeed'
	//    '{'
	//        'expression' expression=Expression
	//    '}';
	public SetSpeedElements getSetSpeedAccess() {
		return pSetSpeed;
	}
	
	public ParserRule getSetSpeedRule() {
		return getSetSpeedAccess().getRule();
	}
	
	//SetClock returns SetClock:
	//    'SetClock'
	//    '{'
	//        'expression' expression=Expression
	//    '}';
	public SetClockElements getSetClockAccess() {
		return pSetClock;
	}
	
	public ParserRule getSetClockRule() {
		return getSetClockAccess().getRule();
	}
	
	//Rotate returns Rotate:
	//    'Rotate'
	//    '{'
	//        'expression' expression=Expression
	//    '}';
	public RotateElements getRotateAccess() {
		return pRotate;
	}
	
	public ParserRule getRotateRule() {
		return getRotateAccess().getRule();
	}
	
	//Forward returns Forward:
	//    'Forward'
	//    '{'
	//        'expression' expression=Expression
	//    '}';
	public ForwardElements getForwardAccess() {
		return pForward;
	}
	
	public ParserRule getForwardRule() {
		return getForwardAccess().getRule();
	}
	
	//Backward returns Backward:
	//    'Backward'
	//    '{'
	//        'expression' expression=Expression
	//    '}';
	public BackwardElements getBackwardAccess() {
		return pBackward;
	}
	
	public ParserRule getBackwardRule() {
		return getBackwardAccess().getRule();
	}
	
	//Leftward returns Leftward:
	//    'Leftward'
	//    '{'
	//        'expression' expression=Expression
	//    '}';
	public LeftwardElements getLeftwardAccess() {
		return pLeftward;
	}
	
	public ParserRule getLeftwardRule() {
		return getLeftwardAccess().getRule();
	}
	
	//Rightward returns Rightward:
	//    'Rightward'
	//    '{'
	//        'expression' expression=Expression
	//    '}';
	public RightwardElements getRightwardAccess() {
		return pRightward;
	}
	
	public ParserRule getRightwardRule() {
		return getRightwardAccess().getRule();
	}
	
	//enum BinaryOp returns BinaryOp:
	//                AND = 'AND' | OR = 'OR' | NOT = 'NOT' | EQUAL = 'EQUAL' | LESSOREQUAL = 'LESSOREQUAL' | GREATEROREQUAL = 'GREATEROREQUAL' | LESS = 'LESS' | GREATER = 'GREATER' | PLUS = 'PLUS' | MINUS = 'MINUS' | TIMES = 'TIMES' | DIVIDE = 'DIVIDE' | MODULO = 'MODULO';
	public BinaryOpElements getBinaryOpAccess() {
		return eBinaryOp;
	}
	
	public EnumRule getBinaryOpRule() {
		return getBinaryOpAccess().getRule();
	}
	
	//enum UnaryOp returns UnaryOp:
	//                NOTEQUAL = 'NOTEQUAL' | NEGATE = 'NEGATE';
	public UnaryOpElements getUnaryOpAccess() {
		return eUnaryOp;
	}
	
	public EnumRule getUnaryOpRule() {
		return getUnaryOpAccess().getRule();
	}
	
	//enum Sensor returns Sensor:
	//                Distance = 'Distance' | Color = 'Color';
	public SensorElements getSensorAccess() {
		return eSensor;
	}
	
	public EnumRule getSensorRule() {
		return getSensorAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
