/*
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.robotml.RobotMLRuntimeModule;
import org.xtext.robotml.RobotMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RobotMLIdeSetup extends RobotMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RobotMLRuntimeModule(), new RobotMLIdeModule()));
	}
	
}
