/*
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RobotMLUiModule extends AbstractRobotMLUiModule {

	public RobotMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
