<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="robotML" nsURI="http://www.example.org/robotML" nsPrefix="robotML">
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDeclaration" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RobotML">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" lowerBound="1"
        upperBound="-1" eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignation" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Statement #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functiondeclaration" lowerBound="1"
        eType="#//FunctionDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cast">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1" eType="#//Unit"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        upperBound="2" eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" abstract="true" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1" eType="#//Block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="#//Loop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foreach" eSuperTypes="#//Loop">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Binary" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operands" lowerBound="2"
        upperBound="2" eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Operator" eType="#//Operators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unary" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operands" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Operator" eType="#//Operators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Operators">
    <eLiterals name="AND" literal="&amp;&amp;"/>
    <eLiterals name="OR" value="1" literal="||"/>
    <eLiterals name="NOT" value="2" literal="!"/>
    <eLiterals name="NOTEQUAL" value="3" literal="!="/>
    <eLiterals name="EQUAL" value="4" literal="=="/>
    <eLiterals name="LESSOREQUAL" value="5" literal="&lt;="/>
    <eLiterals name="GREATEROREQUAL" value="6" literal=">="/>
    <eLiterals name="LESS" value="7" literal="&lt;"/>
    <eLiterals name="GREATER" value="8" literal=">"/>
    <eLiterals name="PLUS" value="9" literal="+"/>
    <eLiterals name="MINUS" value="10" literal="-"/>
    <eLiterals name="TIMES" value="11" literal="*"/>
    <eLiterals name="DIVIDE" value="12" literal="/"/>
    <eLiterals name="MODULO" value="13" literal="%"/>
  </eClassifiers>
</ecore:EPackage>
