/*
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.robotml.ui.internal.RobotmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RobotMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(RobotmlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		RobotmlActivator activator = RobotmlActivator.getInstance();
		return activator != null ? activator.getInjector(RobotmlActivator.ORG_XTEXT_ROBOTML_ROBOTML) : null;
	}

}
