/*
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RobotMLStandaloneSetup extends RobotMLStandaloneSetupGenerated {

	public static void doSetup() {
		new RobotMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
