/**
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import org.xtext.robotml.services.RobotMLGrammarAccess;
import robotML.Assignation;

@SuppressWarnings("all")
public class RobotMLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private RobotMLGrammarAccess _robotMLGrammarAccess;

  protected void _format(final Assignation assignation, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field variableDecl is undefined for the type Assignation"
      + "\nformat cannot be resolved");
  }

  protected void _format(final /* VariableDeclaration */Object variableDeclaration, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\ntype cannot be resolved"
      + "\nformat cannot be resolved");
  }

  @XbaseGenerated
  public void format(final Object assignation, final IFormattableDocument document) {
    if (assignation instanceof XtextResource) {
      _format((XtextResource)assignation, document);
      return;
    } else if (assignation instanceof Assignation) {
      _format((Assignation)assignation, document);
      return;
    } else if (assignation instanceof EObject) {
      _format((EObject)assignation, document);
      return;
    } else if (assignation == null) {
      _format((Void)null, document);
      return;
    } else if (assignation != null) {
      _format(assignation, document);
      return;
    } else if (assignation != null) {
      _format(assignation, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(assignation, document).toString());
    }
  }
}
