/*
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobotMLScopeProvider extends DelegatingScopeProvider {
}
