/**
 *
 * $Id$
 */
package robotML.validation;

import robotML.Expression;
import robotML.Variable;

/**
 * A sample validator interface for {@link robotML.Foreach}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ForeachValidator {
	boolean validate();

	boolean validateVariable(Variable value);

	boolean validateExpression(Expression value);
}
