/*
 * generated by Xtext 2.41.0
 */
package org.xtext.robotml.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class RobotMLProposalProvider extends AbstractRobotMLProposalProvider {
}
